# Generated by Django 3.2 on 2023-03-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230317_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titles',
            new_name='title',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='author_title'),
        ),
    ]
